spring:
  application:
    name: tcc-service-consumer
  profiles:
    active: dev

server:
  port: 8006

logging:
  config: config/logback.xml

ribbon.ReadTimeout: 120000
ribbon.ConnectTimeout: 30000
feign:
   hystrix:
     enabled: false #开启feign自带的熔断器,默认不开启的
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000000

---
spring:
  profiles: dev
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://172.24.132.108:3306/car_loan?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      username: loan_rm_pro
      password: loan_rm_pro
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 150000
mybatis:
  typeAliasesPackage: com.carloan.service.consumer.**.dto
  mapperLocations: classpath*:com/carloan/service/consumer/*/dao/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/
  instance:
    #是否使用IP定义注册中心的地址
    preferIpAddress: true



