spring:
  application:
    name: tcc-service-provider02
  profiles:
    active: dev

server:
  port: 8008

logging:
  config: config/logback.xml

---
spring:
  profiles: dev
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://172.24.132.108:3306/car_loan?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      username: loan_rm_pro
      password: loan_rm_pro
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 150000
mybatis:
  typeAliasesPackage: com.carloan.service.provider02.**.dto
  mapperLocations: classpath*:com/carloan/service/provider02/*/dao/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/
  instance:
    #是否使用IP定义注册中心的地址
    preferIpAddress: true



