spring:
  application:
    name: carloan-service-shiro
  profiles:
    active: dev

server:
  port: 8002

logging:
  config: config/logback.xml
#接口调用超时时间设置
ribbon:
  ReadTimeout: 25000
  ConnectTimeout: 25000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
feign:
   hystrix:
     enabled: false #开启feign自带的熔断器,默认不开启的
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 75000
---
spring:
  profiles: dev
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://localhost:3306/car_loan?autoReconnect=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 150000
mybatis:
  typeAliasesPackage: com.carloan.service.shiro.**.dto
  mapperLocations: classpath*:com/carloan/service/shiro/*/dao/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9901/eureka/
  instance:
    #是否使用IP定义注册中心的地址
    preferIpAddress: true



